// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
    MainContent: typeof import('./src/components/Layout/MainContent/MainContent.vue')['default']
    NavHeader: typeof import('./src/components/Layout/NavHeader/NavHeader.vue')['default']
    Sidebar: typeof import('./src/components/Layout/Sidebar/Sidebar.vue')['default']
  }
}

export { }
